version: "3"
networks: 
    net:
 
services: 
    mysql:
        image: mysql:5.7
        container_name: mysql  
        tty: true
        ports:
            - "4206:3306"
        volumes:
            - "./bd:/var/lib/mysql"
        environment: 
            MYSQL_ROOT_PASSWORD: admin
        networks: 
            - net
    server:
        image: prestashop/prestashop:1.7.8.5
        container_name: web
        ports:
            - "80:80"
        volumes:
            - "./web:/var/www/html"
        environment:
            DB_SERVER: mysql 
        depends_on:  
            - mysql
        networks: 
            - net
